language: node_js

node_js:
  - "6"

addons:
  firefox: "49.0"
cache:
  directories:
    - node_modules
branches:
  only: master

notifications:
  email: false

install:
  - npm install

script:
  - npm run test:cov

after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash) -t 25124aef-9e66-49f5-90f2-4b48b7ca602f